### ISSUE TITLE
Add bar code scanning capabilities. Code 39 and QR code

### ISSUE THREAD

**Issue by stevexero** [stevexero/bim#1]
@Cservice01

To have these capabilities, I'll be getting started on a mobile app.  This app should be cross-platform, allowing anyone (with credentials) to use it.  I'll be looking at tools and frameworks like React Native and Expo, which can easily be integrated into the BoxValet database.  I'll start with just the qr and code 39 capabilities.

*** Update 8/7/24
Pivoting to having this web hosted.

**Comment by stevexero** [comment]
Libraries used:
https://github.com/mebjas/html5-qrcode?tab=readme-ov-file

React Implementation:
https://github.com/scanapp-org/html5-qrcode-react?tab=readme-ov-file

**Comment by stevexero** [comment]
Check functionality for Chrome on Android (and other browser's, too)

**Comment by Cservice01** [comment]
Chrome CHECK, Android CHECK, IPhone CHECK........... 👍

**Comment by Cservice01** [comment]
FUCK YEAH!!!!
